# Generated by Django 5.1.4 on 2024-12-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del paciente (ej: 12345678-9)', max_length=12, unique=True)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=100)),
                ('fecha_atencion', models.DateField()),
                ('hora_atencion', models.TimeField()),
            ],
        ),
    ]
